# Generated by Django 3.2.20 on 2023-08-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_last_date', models.DateField()),
                ('product_description', models.TextField()),
                ('product_price', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
