# Generated by Django 4.2 on 2023-08-17 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_before_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 2, 7, 58, 819824)),
        ),
    ]
