# Generated by Django 3.2.20 on 2023-08-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_busket', models.CharField(max_length=100)),
                ('weight_busket', models.PositiveSmallIntegerField()),
                ('capacity_busket', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
