# Generated by Django 3.2.20 on 2023-08-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_busket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_2', models.CharField(max_length=255)),
                ('product_last_date_2', models.DateField()),
                ('product_description_2', models.TextField()),
                ('product_price_2', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Product_2',
                'verbose_name_plural': 'Products_2',
            },
        ),
    ]
