# Generated by Django 3.2.20 on 2023-08-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busket',
            name='capacity_busket',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
