# Generated by Django 4.2 on 2023-08-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_busket_capacity_busket'),
    ]

    operations = [
        migrations.AddField(
            model_name='busket',
            name='products_in_busket',
            field=models.TextField(default='potato', max_length=500),
            preserve_default=False,
        ),
    ]
