# Generated by Django 4.2 on 2023-08-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_busket_products_in_busket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_2',
            name='product_last_date_2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
