# Generated by Django 3.2.20 on 2023-08-10 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20230810_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='product_2',
            name='product_last_date_2',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 20, 45, 9, 238743)),
        ),
    ]
