# Generated by Django 3.2.20 on 2023-08-10 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20230810_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_last_date', models.DateField()),
                ('product_description', models.TextField()),
                ('product_price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product_2',
            name='product_last_date_2',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 22, 51, 21, 248901)),
        ),
    ]
