# Generated by Django 4.2 on 2023-08-14 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_product_2_product_last_date_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_descript', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'desc',
                'verbose_name_plural': 'descriptions',
            },
        ),
        migrations.AlterField(
            model_name='product_2',
            name='product_last_date_2',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 13, 18, 27, 345405)),
        ),
    ]
