# Generated by Django 4.2 on 2023-08-14 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_desc_alter_product_2_product_last_date_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_2',
            name='busket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.busket'),
        ),
        migrations.AddField(
            model_name='product_2',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.desc'),
        ),
        migrations.AlterField(
            model_name='product_2',
            name='product_last_date_2',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 19, 21, 5, 82661)),
        ),
    ]
