# Generated by Django 4.2 on 2023-08-14 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_product_2_busket_product_2_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_2',
            name='product_last_date_2',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 19, 43, 57, 446059)),
        ),
    ]
